# Generated by Django 4.2.30 on 2026-09-09 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='frequency',
            field=models.IntegerField(default=0, help_text='How often this problem appears in interviews (0-100)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='True if LeetCode Premium-only problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='leetcode_id',
            field=models.IntegerField(blank=True, help_text='LeetCode problem ID number', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('data_structure', 'Data Structure'), ('algorithm', 'Algorithm'), ('technique', 'Technique')], default='algorithm', max_length=20),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Hex color for badge styling, e.g. #3b82f6', max_length=7),
        ),
        migrations.AddField(
            model_name='userproblemprogress',
            name='total_time_spent_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('password_reset_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmarked_problems', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='tracker.problem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
