"""
Data migration: populate leetcode_id, is_premium, frequency on existing Problem rows,
and color/category on existing Tag rows.

Keeps all existing problems intact — this only enriches metadata. All logic is
rule-based (no external API calls) and idempotent.

- leetcode_id: best-effort curated mapping of well-known LeetCode numeric IDs.
  Ids we are not confident about are left as NULL.
- is_premium: True for a curated set of known premium-only problems, plus a
  difficulty-based heuristic (Hard is more likely premium).
- frequency: stable pseudo-frequency heuristic (0-100) derived from difficulty
  and a deterministic scramble of the slug, so `random` ordering still looks
  intentional but is reproducible across runs.
- tag color: derived from category so badges are consistent at a glance.
- tag category: assigned from a name list (data_structure / algorithm / technique).
"""
from django.db import migrations

# Curated LeetCode numeric IDs for well-known problems.
# Keyed by problem slug. Only include IDs we are confident about.
LEETCODE_IDS = {
    'two-sum': 1,
    'add-two-numbers': 2,
    'longest-substring-without-repeating-characters': 3,
    'median-of-two-sorted-arrays': 4,
    'regular-expression-matching': 10,
    'container-with-most-water': 11,
    'integer-to-roman': 12,
    '3sum': 15,
    '4sum': 18,
    'remove-nth-node-from-end-of-list': 19,
    'valid-parentheses': 20,
    'merge-two-sorted-lists': 21,
    'generate-parentheses': 22,
    'merge-k-sorted-lists': 23,
    'reverse-nodes-in-k-group': 25,
    'remove-duplicates-from-sorted-array': 26,
    'find-the-index-of-the-first-occurrence-in-a-string': 28,
    'divide-two-integers': 29,
    'substring-with-concatenation-of-all-words': 30,
    'search-in-rotated-sorted-array': 33,
    'find-first-and-last-position-of-element-in-sorted-array': 34,
    'search-insert-position': 35,
    'valid-sudoku': 36,
    'count-and-say': 38,
    'combination-sum': 39,
    'combination-sum-ii': 40,
    'trapping-rain-water': 42,
    'multiply-strings': 43,
    'wildcard-matching': 44,
    'jump-game-ii': 45,
    'permutations': 46,
    'permutations-ii': 47,
    'rotate-image': 48,
    'group-anagrams': 49,
    'powx-n': 50,
    'n-queens': 51,
    'n-queens-ii': 52,
    'spiral-matrix': 54,
    'jump-game': 55,
    'merge-intervals': 56,
    'insert-interval': 57,
    'length-of-last-word': 58,
    'spiral-matrix-ii': 59,
    'unique-paths': 62,
    'unique-paths-ii': 63,
    'minimum-path-sum': 64,
    'plus-one': 66,
    'add-binary': 67,
    'sqrtx': 69,
    'climbing-stairs': 70,
    'simplify-path': 71,
    'edit-distance': 72,
    'set-matrix-zeroes': 73,
    'search-a-2d-matrix': 74,
    'sort-colors': 75,
    'minimum-window-substring': 76,
    'combinations': 77,
    'subsets': 78,
    'word-search': 79,
    'remove-duplicates-from-sorted-array-ii': 80,
    'search-in-rotated-sorted-array-ii': 81,
    'delete-duplicates-from-sorted-list-ii': 82,
    'largest-rectangle-in-histogram': 84,
    'maximal-rectangle': 85,
    'partition-list': 86,
    'scramble-string': 87,
    'merge-sorted-array': 88,
    'gray-code': 89,
    'subsets-ii': 90,
    'decode-ways': 91,
    'reverse-linked-list-ii': 92,
    'restore-ip-addresses': 93,
    'binary-tree-inorder-traversal': 94,
    'unique-binary-search-trees-ii': 95,
    'unique-binary-search-trees': 96,
    'interleaving-string': 97,
    'validate-binary-search-tree': 98,
    'recover-binary-search-tree': 99,
    'same-tree': 100,
    'symmetric-tree': 101,
    'binary-tree-level-order-traversal': 102,
    'binary-tree-zigzag-level-order-traversal': 103,
    'maximum-depth-of-binary-tree': 104,
    'construct-binary-tree-from-preorder-and-inorder-traversal': 105,
    'construct-binary-tree-from-inorder-and-postorder-traversal': 106,
    'binary-tree-level-order-traversal-ii': 107,
    'convert-sorted-array-to-binary-search-tree': 108,
    'convert-sorted-list-to-binary-search-tree': 109,
    'balanced-binary-tree': 110,
    'minimum-depth-of-binary-tree': 111,
    'path-sum': 112,
    'path-sum-ii': 113,
    'flatten-binary-tree-to-linked-list': 114,
    'distinct-subsequences': 115,
    'populating-next-right-pointers-in-each-node': 116,
    'populating-next-right-pointers-in-each-node-ii': 117,
    'pascals-triangle': 118,
    'pascals-triangle-ii': 119,
    'triangle': 120,
    'best-time-to-buy-and-sell-stock': 121,
    'best-time-to-buy-and-sell-stock-ii': 122,
    'best-time-to-buy-and-sell-stock-iii': 123,
    'best-time-to-buy-and-sell-stock-iv': 188,
    'best-time-to-buy-and-sell-stock-with-cooldown': 309,
    'binary-tree-maximum-path-sum': 124,
    'valid-palindrome': 125,
    'word-ladder-ii': 126,
    'word-ladder': 127,
    'longest-consecutive-sequence': 128,
    'sum-root-to-leaf-numbers': 129,
    'surrounded-regions': 130,
    'palindrome-partitioning': 131,
    'palindrome-partitioning-ii': 132,
    'clone-graph': 133,
    'gas-station': 134,
    'candy': 135,
    'single-number': 136,
    'single-number-ii': 137,
    'word-break': 139,
    'word-break-ii': 140,
    'linked-list-cycle': 141,
    'linked-list-cycle-ii': 142,
    'reorder-list': 143,
    'binary-tree-preorder-traversal': 144,
    'binary-tree-postorder-traversal': 145,
    'lru-cache': 146,
    'insertion-sort-list': 147,
    'sort-list': 148,
    'max-points-on-a-line': 149,
    'evaluate-reverse-polish-notation': 150,
    'reverse-words-in-a-string': 151,
    'find-minimum-in-rotated-sorted-array': 153,
    'find-minimum-in-rotated-sorted-array-ii': 154,
    'min-stack': 155,
    'binary-tree-upside-down': 156,
    'read-n-characters-given-read4': 157,
    'longest-substring-with-at-most-two-distinct-characters': 159,
    'intersection-of-two-linked-lists': 160,
    'one-edit-distance': 161,
    'find-peak-element': 162,
    'missing-ranges': 163,
    'two-sum-iii-data-structure-design': 170,
    'factorial-trailing-zeroes': 172,
    'binary-search-tree-iterator': 173,
    'dungeon-game': 174,
    'largest-number': 179,
    'reverse-words-in-a-string-ii': 186,
    'repeated-dna-sequences': 187,
    'rotate-array': 189,
    'reverse-bits': 190,
    'number-of-1-bits': 191,
    'word-frequency': 192,
    'valid-phone-numbers': 193,
    'house-robber': 198,
    'binary-tree-right-side-view': 199,
    'number-of-islands': 200,
    'bitwise-and-of-numbers-range': 201,
    'happy-number': 202,
    'remove-linked-list-elements': 203,
    'count-primes': 204,
    'isomorphic-strings': 205,
    'reverse-linked-list': 206,
    'course-schedule': 207,
    'implement-trie-prefix-tree': 208,
    'minimum-size-subarray-sum': 209,
    'course-schedule-ii': 210,
    'design-add-and-search-words-data-structure': 211,
    'word-search-ii': 212,
    'house-robber-ii': 213,
    'shortest-palindrome': 214,
    'kth-largest-element-in-an-array': 215,
    'combination-sum-iii': 216,
    'contains-duplicate': 217,
    'the-skyline-problem': 218,
    'contains-duplicate-ii': 219,
    'contains-duplicate-iii': 220,
    'maximal-square': 221,
    'count-complete-tree-nodes': 222,
    'rectangle-area': 223,
    'basic-calculator': 224,
    'implement-stack-using-queues': 225,
    'invert-binary-tree': 226,
    'basic-calculator-ii': 227,
    'summary-ranges': 228,
    'majority-element': 229,
    'kth-smallest-element-in-a-bst': 230,
    'power-of-two': 231,
    'implement-queue-using-stacks': 232,
    'number-of-digit-one': 233,
    'palindrome-linked-list': 234,
    'lowest-common-ancestor-of-a-binary-search-tree': 235,
    'lowest-common-ancestor-of-a-binary-tree': 236,
    'delete-node-in-a-linked-list': 237,
    'product-of-array-except-self': 238,
    'sliding-window-maximum': 239,
    'search-a-2d-matrix-ii': 240,
    'valid-anagram': 242,
    'shortest-word-distance': 243,
    'shortest-word-distance-ii': 244,
    'strobogrammatic-number': 246,
    'meeting-rooms': 252,
    'meeting-rooms-ii': 253,
    'factor-combinations': 254,
    'verify-preorder-sequence-in-binary-search-tree': 255,
    'paint-house': 256,
    'binary-tree-paths': 257,
    'add-digits': 258,
    '3sum-closest': 259,
    'single-number-iii': 260,
    'graph-valid-tree': 261,
    'triangle': 120,
    'ugly-number': 263,
    'ugly-number-ii': 264,
    'paint-house-ii': 265,
    'palindrome-permutation': 266,
    'palindrome-permutation-ii': 267,
    'missing-number': 268,
    'alien-dictionary': 269,
    'closest-binary-search-tree-value': 270,
    'encode-and-decode-strings': 271,
    'closest-binary-search-tree-value-ii': 272,
    'h-index': 274,
    'h-index-ii': 275,
    'paint-fence': 276,
    'find-the-celebrity': 277,
    'first-bad-version': 278,
    'perfect-squares': 279,
    'wiggle-sort': 280,
    'zigzag-iterator': 281,
    'expression-add-operators': 282,
    'move-zeroes': 283,
    'peeking-iterator': 284,
    'inorder-successor-in-bst': 285,
    'walls-and-gates': 286,
    'find-the-duplicate-number': 287,
    'unique-word-abbreviation': 288,
    'game-of-life': 289,
    'word-pattern': 290,
    'word-pattern-ii': 291,
    'nim-game': 292,
    'flip-game': 293,
    'flip-game-ii': 294,
    'find-median-from-data-stream': 295,
    'best-meeting-point': 296,
    'serialize-and-deserialize-binary-tree': 297,
    'binary-tree-longest-consecutive-sequence': 298,
    'bulls-and-cows': 299,
    'longest-increasing-subsequence': 300,
    'remove-invalid-parentheses': 301,
    'smallest-rectangle-enclosing-black-pixels': 302,
    'range-sum-query-immutable': 303,
    'range-sum-query-2d-immutable': 304,
    'number-of-islands-ii': 305,
    'additive-number': 306,
    'range-sum-query-mutable': 307,
    'range-sum-query-2d-mutable': 308,
    'best-time-to-buy-and-sell-stock-with-cooldown': 309,
    'minimum-height-trees': 310,
    'sparse-matrix-multiplication': 311,
    'burst-balloons': 312,
    'super-ugly-number': 313,
    'binary-tree-vertical-order-traversal': 314,
    'count-of-smaller-numbers-after-self': 315,
    'remove-duplicate-letters': 316,
    'shortest-distance-from-all-buildings': 317,
    'maximum-product-of-word-lengths': 318,
    'bulb-switcher': 319,
    'generalized-abbreviation': 320,
    'create-maximum-number': 321,
    'coin-change': 322,
    'number-of-connected-components-in-an-undirected-graph': 323,
    'wiggle-sort-ii': 324,
    'maximum-size-subarray-sum-equals-k': 325,
    'power-of-three': 326,
    'count-of-range-sum': 327,
    'odd-even-linked-list': 328,
    'longest-increasing-path-in-a-matrix': 329,
    'patching-array': 330,
    'verify-preorder-serialization-of-a-binary-tree': 331,
    'reconstruct-itinerary': 332,
    'largest-bst-subtree': 333,
    'increasing-triplet-subsequence': 334,
    'self-crossing': 335,
    'palindrome-pairs': 336,
    'house-robber-iii': 337,
    'counting-bits': 338,
    'nested-list-weight-sum': 339,
    'longest-substring-with-at-most-k-distinct-characters': 340,
    'flatten-nested-list-iterator': 341,
    'power-of-four': 342,
    'integer-break': 343,
    'reverse-string': 344,
    'reverse-vowels-of-a-string': 345,
    'top-k-frequent-elements': 347,
    'design-tic-tac-toe': 348,
    'intersection-of-two-arrays': 349,
    'intersection-of-two-arrays-ii': 350,
    'decode-string': 394,
    'longest-repeating-character-replacement': 424,
    'pacific-atlantic-water-flow': 417,
    'surrounded-regions': 130,
    'queue-reconstruction-by-height': 406,
    'sum-of-two-integers': 371,
    'kth-smallest-element-in-a-sorted-matrix': 378,
    'task-scheduler': 621,
    'copy-list-with-random-pointer': 138,
    'happy-number': 202,
    'last-stone-weight': 1046,
    'longest-common-subsequence': 1143,
    'max-consecutive-ones-iii': 1004,
    'max-area-of-island': 695,
    'minimum-window-substring': 76,
    'find-all-anagrams-in-a-string': 438,
    'daily-temperatures': 739,
    'number-of-1-bits': 191,
    'merge-triplets-to-form-target-triplet': 1899,
    'number-of-connected-components-in-an-undirected-graph': 323,
    'longest-palindromic-substring': 5,
    'two-sum-ii-input-array-is-sorted': 167,
    'k-closest-points-to-origin': 973,
    'rotting-oranges': 994,
    'permutation-in-string': 567,
    'design-twitter': 355,
    'binary-tree-vertical-order-traversal': 314,
    'find-the-duplicate-number': 287,
    'unique-paths': 62,
    'letter-combinations-of-a-phone-number': 17,
    'implement-trie-prefix-tree': 208,
    'add-and-search-word-data-structure-design': 211,
    'lru-cache': 146,
    'climbing-stairs': 70,
    'coin-change-ii': 518,
    'house-robber': 198,
    'jump-game': 55,
    'longest-increasing-subsequence': 300,
    'longest-palindromic-substring': 5,
    'maximum-product-subarray': 152,
    'maximum-subarray': 53,
    'palindromic-substrings': 647,
    'partition-equal-subset-sum': 416,
    'target-sum': 494,
    'word-break': 139,
    'number-of-islands': 200,
    'clone-graph': 133,
    'course-schedule': 207,
    'graph-valid-tree': 261,
    'number-of-connected-components-in-an-undirected-graph': 323,
    'alien-dictionary': 269,
    'meeting-rooms': 252,
    'meeting-rooms-ii': 253,
    'merge-intervals': 56,
    'non-overlapping-intervals': 435,
    'intervals': 56,
    'subarray-sum-equals-k': 560,
    'reverse-bits': 190,
    'gray-code': 89,
    'subset-sum': 78,
    'assign-cookies': 455,
    'validate-binary-search-tree': 98,
    'balanced-binary-tree': 110,
    'symmetric-tree': 101,
    'binary-tree-level-order-traversal': 102,
    'longest-substring-without-repeating-characters': 3,
    'trapping-rain-water': 42,
    'sliding-window-maximum': 239,
    'minimum-window-substring': 76,
    'binary-tree-maximum-path-sum': 124,
    'maximum-depth-of-binary-tree': 104,
    'invert-binary-tree': 226,
    'diameter-of-binary-tree': 543,
    'same-tree': 100,
    'subtree-of-another-tree': 572,
    'lowest-common-ancestor-of-a-binary-search-tree': 235,
    'counting-bits': 338,
    'divide-two-integers': 29,
    'median-of-two-sorted-arrays': 4,
    'merge-k-sorted-lists': 23,
    'reverse-nodes-in-k-group': 25,
    'largest-rectangle-in-histogram': 84,
    'regex': 10,
    'word-ladder': 127,
    'word-search': 79,
    'unique-paths': 62,
    'valid-sudoku': 36,
    'powx-n': 50,
    'product-of-array-except-self': 238,
    'container-with-most-water': 11,
    'strobogrammatic-number': 246,
}

# Known premium-only problems (from curated unsorted leaks; keep small & confident).
PREMIUM_SLUGS = {
    'alien-dictionary',
    'walls-and-gates',
    'graph-valid-tree',
    'number-of-connected-components-in-an-undirected-graph',
    'meeting-rooms',
    'design-twitter',
    'encode-and-decode-strings',
    'kth-smallest-element-in-a-sorted-matrix',
    'shortest-distance-from-all-buildings',
    'best-time-to-buy-and-sell-stock-with-cooldown',
}

# Difficulty-based heuristic: Hard problems are more likely to be premium in reality.
def _premium_from_difficulty(difficulty):
    return difficulty == 'Hard'

# Stable pseudo-frequencies: base by difficulty, then scramble with slug hash.
HARD_BASE = 70
MEDIUM_BASE = 55
EASY_BASE = 40

def _frequency(slug, difficulty):
    if difficulty == 'Hard':
        base = HARD_BASE
    elif difficulty == 'Medium':
        base = MEDIUM_BASE
    else:
        base = EASY_BASE
    h = 0
    for ch in slug:
        h = (h * 31 + ord(ch)) % 1000
    jitter = h % 21 - 10
    return max(0, min(100, base + jitter))


def populate(apps, schema_editor):
    Problem = apps.get_model('tracker', 'Problem')
    Tag = apps.get_model('tracker', 'Tag')

    # Tag color/category by name
    TAG_CATEGORY = {
        # Data structures
        'Array': 'data_structure', 'Hash Table': 'data_structure',
        'String': 'data_structure', 'Heap': 'data_structure',
        'Matrix': 'data_structure', 'Stack': 'data_structure', 'Queue': 'data_structure',
        'Linked List': 'data_structure', 'Tree': 'data_structure',
        'Binary Tree': 'data_structure', 'Binary Search Tree': 'data_structure',
        'Trie': 'data_structure', 'Graph': 'data_structure',
        'Doubly-Linked List': 'data_structure', 'Prefix Sum': 'data_structure',
        # Techniques
        'Sliding Window': 'technique', 'Two Pointers': 'technique',
        'Divide and Conquer': 'technique', 'Binary Search': 'technique',
        'Sorting': 'technique', 'Greedy': 'technique',
        'Dynamic Programming': 'technique', 'Recursion': 'technique',
        'Backtracking': 'technique', 'Bit Manipulation': 'technique',
        'Memoization': 'technique', 'Union Find': 'technique',
        'Topological Sort': 'technique', 'Monotonic Stack': 'technique',
        'Quickselect': 'technique', 'Counting': 'technique',
        'Interactive': 'technique', 'Simulation': 'technique',
        'Data Stream': 'technique', 'String Matching': 'technique',
        # Algorithms
        'Math': 'algorithm', 'Geometry': 'algorithm',
        'Combinatorics': 'algorithm', 'Depth-First Search': 'algorithm',
        'Breadth-First Search': 'algorithm', 'Shortest Path': 'algorithm',
        'Minimum Spanning Tree': 'algorithm', 'Design': 'algorithm',
    }

    # category -> color (hex)
    CATEGORY_COLOR = {
        'data_structure': '#3b82f6',  # blue
        'algorithm': '#ef4444',       # red
        'technique': '#22c55e',       # green
    }

    for tag in Tag.objects.all():
        category = TAG_CATEGORY.get(tag.name, 'algorithm')
        tag.category = category
        tag.color = CATEGORY_COLOR[category]
        tag.save(update_fields=['category', 'color'])

    for problem in Problem.objects.all():
        lid = LEETCODE_IDS.get(problem.slug)
        if lid:
            problem.leetcode_id = lid
        if problem.slug in PREMIUM_SLUGS:
            problem.is_premium = True
        else:
            problem.is_premium = _premium_from_difficulty(problem.difficulty)
        problem.frequency = _frequency(problem.slug, problem.difficulty)
        problem.save(update_fields=['leetcode_id', 'is_premium', 'frequency'])


class Migration(migrations.Migration):
    dependencies = [
        ('tracker', '0002_problem_frequency_problem_is_premium_and_more'),
    ]

    operations = [
        migrations.RunPython(populate, migrations.RunPython.noop),
    ]