# Generated by Django 4.2.30 on 2026-09-09 08:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_populate_problem_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=30)),
                ('explanation', models.TextField(blank=True, default='')),
                ('time_complexity', models.CharField(blank=True, default='', max_length=100)),
                ('space_complexity', models.CharField(blank=True, default='', max_length=100)),
                ('source_url', models.URLField(max_length=500)),
                ('last_fetched_at', models.DateTimeField(auto_now=True)),
                ('fetch_failed', models.BooleanField(default=False)),
                ('fetch_error', models.TextField(blank=True, default='')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_solution', to='tracker.problem')),
            ],
            options={
                'ordering': ['-last_fetched_at'],
            },
        ),
    ]
