# Generated by Django 4.2.30 on 2026-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblemprogress',
            name='code_language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript'), ('c', 'C'), ('go', 'Go')], default='python', max_length=30),
        ),
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript'), ('c', 'C'), ('go', 'Go')], default='python', max_length=30),
        ),
    ]
