# Generated by Django 4.2.30 on 2026-09-10 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userproblemprogress_code_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Scraped problem statement description'),
        ),
        migrations.AddField(
            model_name='solution',
            name='question_number',
            field=models.IntegerField(blank=True, help_text='LeetCode problem number', null=True),
        ),
        migrations.CreateModel(
            name='CompanyProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_period', models.CharField(blank=True, default='', help_text='e.g. Thirty Days, Three Months, Six Months, More Than Six Months, All', max_length=100)),
                ('frequency', models.FloatField(default=0.0, help_text='Interview frequency percentage from CSV')),
                ('acceptance_rate', models.FloatField(blank=True, help_text='Acceptance rate from CSV', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_problem_records', to='tracker.company')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_problem_records', to='tracker.problem')),
            ],
            options={
                'ordering': ['-frequency', 'problem__title'],
                'unique_together': {('company', 'problem', 'time_period')},
            },
        ),
    ]
