# Generated by Django 4.2.30 on 2026-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_solution_description_solution_question_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_source_url',
            field=models.URLField(blank=True, default='', help_text='Dedicated solution page URL on leetcode.ca (e.g. /YYYY-MM-DD-{id}-slug/)', max_length=500),
        ),
        migrations.AlterField(
            model_name='solution',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
