# Generated by Django 4.2.30 on 2026-09-12 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0007_solution_solution_source_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('icon', models.CharField(blank=True, default='🏆', max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('required_solve_count', models.IntegerField(blank=True, null=True)),
                ('required_streak_days', models.IntegerField(blank=True, null=True)),
                ('required_difficulty', models.CharField(blank=True, default='', max_length=10)),
                ('required_tag_slug', models.CharField(blank=True, default='', max_length=120)),
                ('required_challenge_count', models.IntegerField(blank=True, null=True)),
                ('required_accepted_count', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('template', models.CharField(choices=[('COUNT', 'Count Challenge'), ('TIMED', 'Timed Challenge'), ('TOPIC', 'Topic Challenge'), ('DIFFICULTY', 'Difficulty Challenge'), ('COMPANY', 'Company Challenge'), ('DEADLINE', 'Deadline Challenge'), ('REVIEW', 'Review Challenge'), ('CUSTOM', 'Custom Challenge')], default='CUSTOM', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('target_count', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=0)),
                ('bonus_points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('difficulty_filter', models.CharField(blank=True, default='', max_length=10)),
                ('completed_count', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.company')),
                ('topic_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('weekly', models.IntegerField(default=0)),
                ('challenge_points', models.IntegerField(default=0)),
                ('streak_points', models.IntegerField(default=0)),
                ('last_weekly_reset', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden test cases are NEVER returned to the frontend. Only verdict + pass/fail count is returned.')),
                ('input_text', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('time_limit_seconds', models.FloatField(blank=True, null=True)),
                ('memory_limit_mb', models.IntegerField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='tracker.problem')),
            ],
            options={
                'ordering': ['problem', 'is_hidden', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java')], max_length=20)),
                ('source_code', models.TextField()),
                ('verdict', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('COMPILE_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('SYSTEM_ERROR', 'Internal Error')], default='PENDING', max_length=20)),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_total', models.IntegerField(default=0)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('memory_kb', models.IntegerField(default=0)),
                ('compile_error', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tracker.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('REVIEW_DUE', 'Reviews Due'), ('CHALLENGE_EXPIRING', 'Challenge Expiring Soon'), ('CHALLENGE_COMPLETED', 'Challenge Completed'), ('ACHIEVEMENT_UNLOCKED', 'Achievement Unlocked'), ('STREAK_MILESTONE', 'Streak Milestone'), ('STUDY_PLAN_BEHIND', 'Study Plan Behind'), ('INTERVIEW_RESULT', 'Interview Result'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanguageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java')], max_length=20)),
                ('starter_code', models.TextField(blank=True, default='')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_templates', to='tracker.problem')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_minutes', models.IntegerField(default=45)),
                ('num_problems', models.IntegerField(default=2)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Mixed', 'Mixed')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solved', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.problem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_problems', to='tracker.interviewsession')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.submission')),
            ],
        ),
        migrations.CreateModel(
            name='DSAPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('problems', models.ManyToManyField(blank=True, related_name='patterns', to='tracker.problem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_problems', to='tracker.challenge')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PROBLEM_VIEWED', 'Problem Viewed'), ('CODE_RUN', 'Code Run'), ('SUBMISSION_CREATED', 'Submission Created'), ('SUBMISSION_ACCEPTED', 'Submission Accepted'), ('REVIEW_COMPLETED', 'Review Completed'), ('PROBLEM_REVISIT', 'Problem Marked Revisit'), ('BOOKMARK_ADDED', 'Bookmark Added'), ('NOTE_UPDATED', 'Note Updated'), ('CHALLENGE_STARTED', 'Challenge Started'), ('CHALLENGE_COMPLETED', 'Challenge Completed'), ('INTERVIEW_STARTED', 'Interview Started'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('ACHIEVEMENT_UNLOCKED', 'Achievement Unlocked'), ('POINTS_AWARDED', 'Points Awarded')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem'], name='tracker_sub_user_id_b0538d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-created_at'], name='tracker_sub_user_id_af82bd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='tracker_not_user_id_57a19e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='languagetemplate',
            unique_together={('problem', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='interviewproblem',
            unique_together={('session', 'problem')},
        ),
        migrations.AlterUniqueTogether(
            name='challengeproblem',
            unique_together={('challenge', 'problem')},
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['user', 'status'], name='tracker_cha_user_id_b2194b_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', 'event_type'], name='tracker_act_user_id_7bbe7b_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', '-created_at'], name='tracker_act_user_id_32587b_idx'),
        ),
    ]
