# Generated by Django 4.2.30 on 2026-09-12 08:37

from django.db import migrations, models


def populate_question_numbers(apps, schema_editor):
    Problem = apps.get_model('tracker', 'Problem')
    existing_numbers = set(
        Problem.objects.filter(leetcode_id__isnull=False).values_list('leetcode_id', flat=True)
    )
    next_num = (max(existing_numbers) if existing_numbers else 0) + 1

    for problem in Problem.objects.all():
        if problem.leetcode_id is not None:
            problem.question_number = problem.leetcode_id
        else:
            problem.question_number = next_num
            problem.leetcode_id = next_num
            next_num += 1
        problem.save(update_fields=['question_number', 'leetcode_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_v2_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['question_number', 'title']},
        ),
        migrations.AddField(
            model_name='problem',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Canonical user-facing unique problem number (e.g. 1 for Two Sum, 42 for Trapping Rain Water)', null=True, unique=True),
        ),
        migrations.RunPython(populate_question_numbers, reverse_code=migrations.RunPython.noop),
    ]
