# Generated by Django 4.2.30 on 2026-09-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_add_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='frequency',
            field=models.IntegerField(db_index=True, default=0, help_text='How often this problem appears in interviews (0-100)'),
        ),
    ]
