# Generated by Django 4.2.30 on 2026-09-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_problem_difficulty_alter_problem_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetemplate',
            name='harness_code',
            field=models.TextField(blank=True, default='', help_text='Driver code appended during execution for function-based problems'),
        ),
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of constraints'),
        ),
        migrations.AddField(
            model_name='problem',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of problem examples [{input, output, explanation}]'),
        ),
        migrations.AddField(
            model_name='problem',
            name='execution_mode',
            field=models.CharField(choices=[('FUNCTION', 'Function-based'), ('STDIN_STDOUT', 'Standard I/O')], db_index=True, default='FUNCTION', help_text='Whether this problem evaluates a function signature or reads from stdin/stdout', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='function_name',
            field=models.CharField(blank=True, default='', help_text='Target function/method name for function-based problems', max_length=100),
        ),
        migrations.AddField(
            model_name='solution',
            name='code_by_language',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of language -> code for multi-language solutions'),
        ),
    ]
