# Generated by Django 4.2.30 on 2026-09-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_online_judge_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='class_name',
            field=models.CharField(blank=True, default='Solution', help_text='Class name enclosing the solution method', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_judge_ready',
            field=models.BooleanField(db_index=True, default=False, help_text='True if problem satisfies complete execution contract'),
        ),
        migrations.AddField(
            model_name='problem',
            name='judge_readiness_status',
            field=models.CharField(choices=[('JUDGE_READY', 'Judge Ready'), ('CONFIGURATION_REQUIRED', 'Configuration Required')], db_index=True, default='CONFIGURATION_REQUIRED', help_text='Canonical judge readiness status', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='missing_configuration',
            field=models.JSONField(blank=True, default=list, help_text='List of missing prerequisites when judge readiness is CONFIGURATION_REQUIRED'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_checker',
            field=models.CharField(choices=[('EXACT', 'Exact'), ('NORMALIZED', 'Normalized'), ('ALTERNATIVES', 'Multiple Valid Alternatives'), ('JSON', 'JSON Equality')], default='NORMALIZED', help_text='Output validator mode for judging solutions', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='parameters_meta',
            field=models.JSONField(blank=True, default=list, help_text='List of parameter definitions [{name: "nums", type: "list[int]"}]'),
        ),
        migrations.AddField(
            model_name='problem',
            name='return_type',
            field=models.CharField(blank=True, default='', help_text='Return type annotation for the method', max_length=100),
        ),
    ]
