# Generated by Django 4.2.30 on 2026-09-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_problem_class_name_problem_is_judge_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True, default='', help_text='Specification of the input format via stdin'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(blank=True, default='', help_text='Specification of the output format via stdout'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='execution_mode',
            field=models.CharField(choices=[('FUNCTION', 'Function-based'), ('STDIN_STDOUT', 'Standard I/O')], db_index=True, default='STDIN_STDOUT', help_text='Whether this problem evaluates a function signature or reads from stdin/stdout', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('COMPILE_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('EXECUTION_ERROR', 'Execution Error'), ('SYSTEM_ERROR', 'Internal Error')], default='PENDING', max_length=20),
        ),
    ]
