# Generated by Django 4.2.30 on 2026-09-12 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_problem_input_format_problem_output_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='memory_limit_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Execution memory limit in megabytes per test case. Fallback to platform default if unset.', null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(1024)]),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Execution time limit in milliseconds per test case. Fallback to difficulty-aware platform default if unset.', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(15000)]),
        ),
    ]
