# Generated by Django 4.2.30 on 2026-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_extend_output_checker_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='preparation_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times preparation has been attempted'),
        ),
        migrations.AddField(
            model_name='problem',
            name='preparation_error',
            field=models.TextField(blank=True, default='', help_text='Last error message from the preparation pipeline, if any'),
        ),
        migrations.AddField(
            model_name='problem',
            name='preparation_last_attempted',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last preparation attempt', null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='preparation_status',
            field=models.CharField(choices=[('PENDING', 'Pending — not yet processed'), ('FETCHING', 'Fetching — network request in progress (or interrupted)'), ('NORMALIZING', 'Normalizing — data processing in progress (or interrupted)'), ('JUDGE_READY', 'Judge Ready — fully prepared'), ('CONFIGURATION_REQUIRED', 'Configuration Required — missing data, not fetchable'), ('FAILED', 'Failed — fetch/prepare error, eligible for retry')], db_index=True, default='PENDING', help_text='Persistent stage of the judge-data preparation pipeline for this problem', max_length=30),
        ),
    ]
