# Generated by Django 4.2.30 on 2026-09-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_problem_preparation_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='focus_topics',
            field=models.ManyToManyField(blank=True, related_name='focused_by_users', to='tracker.tag'),
        ),
    ]
