# Generated by Django 4.2.30 on 2026-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='has_multiple_valid_outputs',
            field=models.BooleanField(db_index=True, default=False, help_text='True if problem allows multiple valid outputs'),
        ),
        migrations.AddField(
            model_name='problem',
            name='judging_mode',
            field=models.CharField(choices=[('stdio', 'Standard I/O'), ('function', 'Function-based')], db_index=True, default='stdio', help_text='Judging mode: stdio or function', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='parameter_schema',
            field=models.JSONField(blank=True, default=list, help_text='Schema definition for function-mode judging'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit_seconds',
            field=models.FloatField(blank=True, help_text='Execution time limit in seconds per test case. Sourced from Problem model.', null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=True, help_text='True if visible sample test case available for Run Code.'),
        ),
    ]
